version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - TZ=${TZ}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mariadb
    command: sh -c "sleep 50 && node server.js"
    networks:
      - app-network


  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - app-network


  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_BASE=${REACT_APP_API_BASE}
    depends_on:
      - backend
    networks:
      - app-network

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    container_name: playit
    network_mode: host
    environment:
      - SECRET_KEY=${PLAYIT_SECRET_KEY}

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"   
      - "8000:8000"   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  portainer_data:
  mariadb_data:

